/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automobile_estate;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DEV SASMAL
 */
public class CARS_IMAGES_WINDOW extends javax.swing.JFrame {

    /**
     * Creates new form CARS_IMAGES_WINDOW
     */
    
    C_TYPE carmake = new C_TYPE();
    HashMap<String, Integer> map = carmake.getTypesMap();
    String car_image_path = "";
    int carid = 0;
    public CARS_IMAGES_WINDOW() {
        initComponents();
        
        //set border to the jpanel title
        Border panel_title_border = BorderFactory.createMatteBorder(0,0,3,0,new Color(255,255,255));
        jPanel_Title.setBorder(panel_title_border);
        
        //set border to the jpanel title
        Border jlabel_image_border = BorderFactory.createMatteBorder(1,1,1,1,new Color(255,255,255));
        jLabel_Image.setBorder(jlabel_image_border);
        
        //populate the combobox with the car make names
        bindCombo();
        
        //when the form show up
        //populate the jtable with all the cars
           fillJtablesCarsData();
           
           //change the jtable row height
        jTable_cars.setRowHeight(40);
        //change the jtable selection background
        jTable_cars.setSelectionBackground(new Color(27,120,77));
        //change the Id column width
        jTable_cars.getColumnModel().getColumn(0).setPreferredWidth(25);
        //change the Address column width
        jTable_cars.getColumnModel().getColumn(1).setPreferredWidth(300);
        
    }
    
    //function for combobox car make
        public void bindCombo()
        {
            for(String s :map.keySet())
            {
                jComboBox_Car_Make.addItem(s);
            }   
        }
        
        //create a function to populate the cars 
        public void fillJtablesCarsData()
    {
        C_CARS cars = new C_CARS();
        ArrayList<C_CARS> carsList= cars.carsList();
            
        //the jtable columns
        String[] colNames = {"id","address"};
        
        //the jtable row
        //ownerslist.size()= the size of the arraylist
        //6 = the number of columns        
        Object[][] rows = new Object[carsList.size()][2];
        
        //add data form the list to the rows 
        for(int i =0; i<carsList.size();i++)
        {
            rows[i][0] = carsList.get(i).getIds();
            rows[i][1] = carsList.get(i).getAddress();
        }
        DefaultTableModel model = new DefaultTableModel(rows,colNames);
        jTable_cars.setModel(model);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_Show_Images = new javax.swing.JButton();
        jButton_Add_Images = new javax.swing.JButton();
        jButton_Remove_Images = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_Car_Make = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_cars = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton_Browse_Images = new javax.swing.JButton();
        jLabel_Image = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel_Title.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Car-Images");

        javax.swing.GroupLayout jPanel_TitleLayout = new javax.swing.GroupLayout(jPanel_Title);
        jPanel_Title.setLayout(jPanel_TitleLayout);
        jPanel_TitleLayout.setHorizontalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_TitleLayout.setVerticalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton_Show_Images.setBackground(new java.awt.Color(0, 102, 255));
        jButton_Show_Images.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jButton_Show_Images.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Show_Images.setText("Show this Cars Images");
        jButton_Show_Images.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Show_Images.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Show_ImagesActionPerformed(evt);
            }
        });

        jButton_Add_Images.setBackground(new java.awt.Color(0, 102, 0));
        jButton_Add_Images.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jButton_Add_Images.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_Images.setText("Add");
        jButton_Add_Images.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_ImagesActionPerformed(evt);
            }
        });

        jButton_Remove_Images.setBackground(new java.awt.Color(255, 0, 0));
        jButton_Remove_Images.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jButton_Remove_Images.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Remove_Images.setText("Remove");
        jButton_Remove_Images.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove_Images.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Remove_ImagesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select a Type:");

        jComboBox_Car_Make.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jComboBox_Car_Make.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Car_MakeActionPerformed(evt);
            }
        });

        jTable_cars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_cars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_carsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_cars);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Image:");

        jButton_Browse_Images.setBackground(new java.awt.Color(255, 255, 0));
        jButton_Browse_Images.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_Browse_Images.setText("Browse");
        jButton_Browse_Images.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Browse_ImagesActionPerformed(evt);
            }
        });

        jLabel_Image.setBackground(new java.awt.Color(255, 102, 255));
        jLabel_Image.setText("     ");
        jLabel_Image.setOpaque(true);

        jList1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        //
        jLabel5.setText("<html>* this table contains the cars id and address.<BR>"
            + "                      click on the button to show the images slider</html>");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        //make the jlabel multiline
        jLabel6.setText("<html>* this list contains the images id of the selected cars.<BR>"
            + "                       (select the car from the table)</html>");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<html>* select an item from ths list to display"
            + "                      or browse an image<BR> from your computer.</html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton_Show_Images, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jButton_Remove_Images, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Add_Images, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Browse_Images, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_Car_Make, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_Car_Make, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton_Browse_Images))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(jLabel_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Show_Images, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Remove_Images, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Add_Images, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Show_ImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Show_ImagesActionPerformed
       try
       {
        //show the selected car images in a slider
        CAR_IMAGES_SLIDER imageSliderform = new CAR_IMAGES_SLIDER();
        
        //set the car id
        int rowIndex = jTable_cars.getSelectedRow(); //selected jtable row index
        int id = Integer.valueOf(jTable_cars.getValueAt(rowIndex, 0).toString()); //get the id from jtable
        imageSliderform.carId = id;// set the id to the slide form
        
        imageSliderform.setVisible(true);
        this.setVisible(false); 
       }
       catch(Exception ex)
       {
            JOptionPane.showMessageDialog(null,"Select The Car First", "Car not Selected",2);
       }
    }//GEN-LAST:event_jButton_Show_ImagesActionPerformed

    private void jButton_Add_ImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_ImagesActionPerformed
       
        //add images to the car
        //multiple images can be added
        //we need to get the car id from the jtable;
        C_CARS car = new C_CARS();
        if(carid != 0)
        {
            if(car.addImages(carid, car_image_path))
            {
                JOptionPane.showMessageDialog(null,"Image Added To This Car", "Add Image",1);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Image Not Added To This Car", "Add Image",2);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Select The Car First", "Car not Selected",2);

        }
    }//GEN-LAST:event_jButton_Add_ImagesActionPerformed

    private void jButton_Remove_ImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove_ImagesActionPerformed
             
        try
        {
            //remove the selected image
        String selectedListitem = String.valueOf(jList1.getSelectedValue());
        Integer imageid = Integer.valueOf(selectedListitem);
        
        //show a confirmation message before deleting the type
        int yes_or_no =JOptionPane.showConfirmDialog(null,"Do you Really Want to Delete this Image","Delete Image",JOptionPane.YES_NO_OPTION);
        if(yes_or_no == JOptionPane.YES_OPTION )
        {   
            if(new C_CARS().removeCarImage(imageid))
            {
                JOptionPane.showMessageDialog(null,"Car Image Deleted","Delete Image",1);
                jLabel_Image.setIcon(null);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Operation Failed, Image Not Deleted", "Delete Image",2);

            }
        }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"No Image Selected", "Delete Image",2);
 
        }
    }//GEN-LAST:event_jButton_Remove_ImagesActionPerformed
      
    //create a function to resize the image to the jlabel
    //make thallow a byte[] param
    public ImageIcon resizeImage(String path,byte[] byteImage)
    {
        ImageIcon pic;
        if(byteImage != null) pic =new ImageIcon(byteImage);
        else pic =new ImageIcon(path);
        
        Image img = pic.getImage().getScaledInstance(jLabel_Image.getWidth(), jLabel_Image.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img);
        return image;
    }
    
    private void jButton_Browse_ImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Browse_ImagesActionPerformed
        
          //browse image from the computer  
          JFileChooser fileChooser = new JFileChooser();
          fileChooser.setDialogTitle("Select The Car Image");
          
          fileChooser.setCurrentDirectory(new File("C:\\Users\\DEV SASMAL\\Documents\\Car_Image"));
          
          //file extension
          FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("Images", ".jpg",".png",".jpeg");
          fileChooser.addChoosableFileFilter(fileFilter);
          
          int fileState = fileChooser.showSaveDialog(null);
          
          if(fileState == JFileChooser.APPROVE_OPTION)
          {
              String path = fileChooser.getSelectedFile().getAbsolutePath();
              jLabel_Image.setIcon(resizeImage(path,null));
              car_image_path = path;
          }
    }//GEN-LAST:event_jButton_Browse_ImagesActionPerformed

    private void jComboBox_Car_MakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Car_MakeActionPerformed
        // show cars in the jtable depending on the selected type
        int carmakes = map.get(jComboBox_Car_Make.getSelectedItem().toString());
        
        C_CARS cars = new C_CARS();
        ArrayList<C_CARS> carsList= cars.carsListByCarmake(carmakes);
            
        //the jtable columns
        String[] colNames = {"id","address"};
        
        //the jtable row
        //ownerslist.size()= the size of the arraylist
        //6 = the number of columns        
        Object[][] rows = new Object[carsList.size()][2];
        
        //add data form the list to the rows 
        for(int i =0; i<carsList.size();i++)
        {
            rows[i][0] = carsList.get(i).getIds();
            rows[i][1] = carsList.get(i).getAddress();
        }
        DefaultTableModel model = new DefaultTableModel(rows,colNames);
        jTable_cars.setModel(model);
    }//GEN-LAST:event_jComboBox_Car_MakeActionPerformed

    private void jTable_carsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_carsMouseClicked
        
          // get the car id from the jtable
          //get the selecte row index
          int rowIndex =jTable_cars.getSelectedRow();
          carid = Integer.valueOf(jTable_cars.getValueAt(rowIndex, 0).toString());
          
          //display the selected car iamges list in the jlist 
          fillTypeList();
    }//GEN-LAST:event_jTable_carsMouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        
        //display the selected image from the lsit to jlabel
        //we can suse the hashmap if we wnat like in the car window
        // but here instead we will create a function to the image by id
        String selectedListitem = String.valueOf(jList1.getSelectedValue());
        Integer imageId = Integer.valueOf(selectedListitem);
        byte[] image = new C_CARS().getImageById(carid);
        jLabel_Image.setIcon(resizeImage("",image));
    }//GEN-LAST:event_jList1MouseClicked

    //create a function to populate the jList with the selected car IMAGES id
    public void fillTypeList()
    {
        HashMap<byte[], Integer> imagesList = new C_CARS().carImageList(carid);
        
        DefaultListModel listModel = new DefaultListModel();
        
        int i=0;
        
        for(Integer  id: imagesList.values())
        {
            listModel.add(i,id);
            i++;
        }
        jList1.setModel(listModel);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CARS_IMAGES_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CARS_IMAGES_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CARS_IMAGES_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CARS_IMAGES_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CARS_IMAGES_WINDOW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_Images;
    private javax.swing.JButton jButton_Browse_Images;
    private javax.swing.JButton jButton_Remove_Images;
    private javax.swing.JButton jButton_Show_Images;
    private javax.swing.JComboBox<String> jComboBox_Car_Make;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_cars;
    // End of variables declaration//GEN-END:variables
}
