/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automobile_estate;

import java.awt.Color;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author DEV SASMAL
 */
public class CARS_WINDOW extends javax.swing.JFrame {

    /**
     * Creates new form CARS_WINDOW
     */
    
    C_TYPE carmake = new C_TYPE();
    HashMap<String, Integer> map = carmake.getTypesMap();
    
    public CARS_WINDOW() {
        initComponents();
         //set border to the jpanel title
        Border panel_title_border = BorderFactory.createMatteBorder(0,0,3,0,new Color(26,138,32));
        jPanel_Title.setBorder(panel_title_border);
        
        //set border to the jbuttons
        Border button_border = BorderFactory.createMatteBorder(3,3,3,3,new Color(255,255,255));
        jButton_Add_Cars.setBorder(button_border);
        jButton_Edit_Cars.setBorder(button_border);
        jButton_Remove_Cars.setBorder(button_border);
        jButton_Show_Cars.setBorder(button_border);
        
        bindCombo();
        
    }
    
    //function for combobox car make
        public void bindCombo()
        {
            for(String s :map.keySet())
            {
                jComboBox_Carmake.addItem(s);
            }   
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Ids = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Address = new javax.swing.JTextArea();
        jButton_Edit_Cars = new javax.swing.JButton();
        jButton_Add_Cars = new javax.swing.JButton();
        jButton_Remove_Cars = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_OwnerId = new javax.swing.JTextField();
        jTextField_Price = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton_Search_Car = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSpinner_Seats = new javax.swing.JSpinner();
        jSpinner_AirBags = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSpinner_Cylinders = new javax.swing.JSpinner();
        jCheckBox_Anti_Lock = new javax.swing.JCheckBox();
        jCheckBox_Roof = new javax.swing.JCheckBox();
        jCheckBox_Parking_Sensor = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jTextField_FuelCapa = new javax.swing.JTextField();
        jSpinner_Doors = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSpinner_Age = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jTextField_Car_Model = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jCheckBox_Camera = new javax.swing.JCheckBox();
        jCheckBox_VoiceControl = new javax.swing.JCheckBox();
        jCheckBox_Anti_Theft = new javax.swing.JCheckBox();
        jCheckBox_Maps = new javax.swing.JCheckBox();
        jCheckBox_Fingerprint = new javax.swing.JCheckBox();
        jCheckBox_Speed_Sensor = new javax.swing.JCheckBox();
        jCheckBox_Crash_Sensor = new javax.swing.JCheckBox();
        jButton_Show_Cars = new javax.swing.JButton();
        jComboBox_Carmake = new javax.swing.JComboBox<>();
        jComboBox_Fueltype = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(75, 192, 18));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel_Title.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cars");

        javax.swing.GroupLayout jPanel_TitleLayout = new javax.swing.GroupLayout(jPanel_Title);
        jPanel_Title.setLayout(jPanel_TitleLayout);
        jPanel_TitleLayout.setHorizontalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addGap(624, 624, 624)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_TitleLayout.setVerticalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Address:");

        jTextField_Ids.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jTextArea_Address.setColumns(20);
        jTextArea_Address.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jTextArea_Address.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Address);

        jButton_Edit_Cars.setBackground(new java.awt.Color(0, 102, 255));
        jButton_Edit_Cars.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jButton_Edit_Cars.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Edit_Cars.setText("Edit");
        jButton_Edit_Cars.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Edit_Cars.setSelected(true);
        jButton_Edit_Cars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Edit_CarsActionPerformed(evt);
            }
        });

        jButton_Add_Cars.setBackground(new java.awt.Color(0, 102, 0));
        jButton_Add_Cars.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jButton_Add_Cars.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_Cars.setText("Add");
        jButton_Add_Cars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_CarsActionPerformed(evt);
            }
        });

        jButton_Remove_Cars.setBackground(new java.awt.Color(255, 0, 0));
        jButton_Remove_Cars.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jButton_Remove_Cars.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Remove_Cars.setText("Remove");
        jButton_Remove_Cars.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove_Cars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Remove_CarsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Car Make:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Owner Id:");

        jTextField_OwnerId.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jTextField_Price.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Price(usd):");

        jButton_Search_Car.setBackground(new java.awt.Color(51, 51, 51));
        jButton_Search_Car.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton_Search_Car.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Search_Car.setText("Search");
        jButton_Search_Car.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Search_Car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Search_CarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Seats:");

        jSpinner_Seats.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jSpinner_Seats.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinner_AirBags.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jSpinner_AirBags.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Air Bags:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("Engine Cylinders:");

        jSpinner_Cylinders.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jSpinner_Cylinders.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jCheckBox_Anti_Lock.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCheckBox_Anti_Lock.setText("Anti Lock Braking");

        jCheckBox_Roof.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCheckBox_Roof.setText("Roof");
        jCheckBox_Roof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_RoofActionPerformed(evt);
            }
        });

        jCheckBox_Parking_Sensor.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCheckBox_Parking_Sensor.setText("Parking Sensor");
        jCheckBox_Parking_Sensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_Parking_SensorActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setText("Fuel Capacity:");

        jTextField_FuelCapa.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jSpinner_Doors.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jSpinner_Doors.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setText("Doors:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setText("Age of the Cars:");

        jSpinner_Age.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jSpinner_Age.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel14.setBackground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("* 0 mean brand new");

        jTextField_Car_Model.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel15.setText("Car Model:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel16.setText("Fuel Type:");

        jCheckBox_Camera.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCheckBox_Camera.setText("Camera");
        jCheckBox_Camera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_CameraActionPerformed(evt);
            }
        });

        jCheckBox_VoiceControl.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCheckBox_VoiceControl.setText("Voice Control");

        jCheckBox_Anti_Theft.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCheckBox_Anti_Theft.setText("Anti Theft Alarm");

        jCheckBox_Maps.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCheckBox_Maps.setText("Maps");

        jCheckBox_Fingerprint.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCheckBox_Fingerprint.setText("Finger Print Access");

        jCheckBox_Speed_Sensor.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCheckBox_Speed_Sensor.setText("Speed Sensor");

        jCheckBox_Crash_Sensor.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCheckBox_Crash_Sensor.setText("Crash Sensor");

        jButton_Show_Cars.setBackground(new java.awt.Color(102, 0, 102));
        jButton_Show_Cars.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jButton_Show_Cars.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Show_Cars.setText("Show Cars");
        jButton_Show_Cars.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Show_Cars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Show_CarsActionPerformed(evt);
            }
        });

        jComboBox_Carmake.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jComboBox_Fueltype.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jComboBox_Fueltype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petrol", "Diesel", "Solar" }));
        jComboBox_Fueltype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_FueltypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton_Add_Cars, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButton_Edit_Cars, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButton_Remove_Cars, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jButton_Show_Cars, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jTextField_Price)
                            .addComponent(jTextField_OwnerId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_Ids, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Search_Car, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                            .addComponent(jTextField_Car_Model, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_Carmake, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel16))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSpinner_Cylinders, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinner_Doors, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinner_AirBags, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinner_Seats, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_FuelCapa)
                                            .addComponent(jComboBox_Fueltype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jCheckBox_Parking_Sensor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox_Anti_Lock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jCheckBox_Roof, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSpinner_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jCheckBox_Fingerprint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCheckBox_VoiceControl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCheckBox_Anti_Theft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCheckBox_Maps, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCheckBox_Speed_Sensor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCheckBox_Crash_Sensor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jCheckBox_Camera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Ids)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Search_Car, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinner_Seats, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinner_AirBags, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_Car_Model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSpinner_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_Cylinders, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Camera)
                    .addComponent(jComboBox_Carmake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_OwnerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_Doors, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_VoiceControl))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_FuelCapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_Anti_Theft))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_Fingerprint, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_Maps, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_Speed_Sensor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_Fueltype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(jCheckBox_Parking_Sensor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox_Anti_Lock, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox_Roof))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox_Crash_Sensor)))
                        .addGap(111, 111, 111)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Add_Cars, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Edit_Cars, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Remove_Cars, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Show_Cars, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Edit_CarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Edit_CarsActionPerformed

        //edit the car data
        try
        {   
            int id = Integer.valueOf(jTextField_Ids.getText());
            String car_model = jTextField_Car_Model.getText();
            int carmake = map.get(jComboBox_Carmake.getSelectedItem().toString());
            int ownerId = Integer.valueOf(jTextField_OwnerId.getText());
            int price = Integer.valueOf(jTextField_Price.getText());
            String address = jTextArea_Address.getText();
            int seats = Integer.valueOf(jSpinner_Seats.getValue().toString());
            int airbags = Integer.valueOf(jSpinner_AirBags.getValue().toString());
            int engine = Integer.valueOf(jSpinner_Cylinders.getValue().toString());
            int doors = Integer.valueOf(jSpinner_Doors.getValue().toString());
            int fuel_capa = Integer.valueOf(jTextField_FuelCapa.getText());
            String fueltype = jComboBox_Fueltype.getSelectedItem().toString();
            boolean parking = false;
            boolean antilock = false;
            boolean roof = false;
            int age = Integer.valueOf(jSpinner_Age.getValue().toString());

            boolean camera = false;
            boolean voice = false;
            boolean antitheft = false;
            boolean fingerprint = false;
            boolean maps = false;
            boolean speedsensors = false;
            boolean crashsensor = false;

            
            if(jCheckBox_Parking_Sensor.isSelected()) parking = true;
            if(jCheckBox_Anti_Lock.isSelected()) antilock = true;
            if(jCheckBox_Roof.isSelected()) roof = true;
            if(jCheckBox_Camera.isSelected()) camera = true;
            if(jCheckBox_VoiceControl.isSelected()) voice = true;
            if(jCheckBox_Anti_Theft.isSelected()) antitheft = true;
            if(jCheckBox_Fingerprint.isSelected()) fingerprint = true;
            if(jCheckBox_Maps.isSelected()) maps = true;
            if(jCheckBox_Speed_Sensor.isSelected()) speedsensors = true;
            if(jCheckBox_Crash_Sensor.isSelected()) crashsensor = true;

            C_CARS cars = new C_CARS(id,car_model, carmake, ownerId, price, address, seats, airbags, engine, doors, fuel_capa, fueltype, parking, antilock, roof, age, camera, voice, antitheft, fingerprint, maps, speedsensors, crashsensor);
            if(new C_CARS().editCars(cars))
            {
                    JOptionPane.showMessageDialog(null,"Cars Updated","Edit Cars", 1);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Cars NOT Updated","Edit Cars", 2);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage()+"Enter a Valid Cars Id and Owner Id", "Invalid Data",0);
        }

        
    }//GEN-LAST:event_jButton_Edit_CarsActionPerformed

    private void jButton_Add_CarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_CarsActionPerformed
        //add a new car to the system

        try
        {
            String car_model = jTextField_Car_Model.getText();
            int carmake = map.get(jComboBox_Carmake.getSelectedItem().toString());
            int ownerId = Integer.valueOf(jTextField_OwnerId.getText());
            int price = Integer.valueOf(jTextField_Price.getText());
            String address = jTextArea_Address.getText();
            int seats = Integer.valueOf(jSpinner_Seats.getValue().toString());
            int airbags = Integer.valueOf(jSpinner_AirBags.getValue().toString());
            int engine = Integer.valueOf(jSpinner_Cylinders.getValue().toString());
            int doors = Integer.valueOf(jSpinner_Doors.getValue().toString());
            int fuel_capa = Integer.valueOf(jTextField_FuelCapa.getText());
            String fueltype = jComboBox_Fueltype.getSelectedItem().toString();
            boolean parking = false;
            boolean antilock = false;
            boolean roof = false;
            int age = Integer.valueOf(jSpinner_Age.getValue().toString());

            boolean camera = false;
            boolean voice = false;
            boolean antitheft = false;
            boolean fingerprint = false;
            boolean maps = false;
            boolean speedsensors = false;
            boolean crashsensor = false;

            
            if(jCheckBox_Parking_Sensor.isSelected()) parking = true;
            if(jCheckBox_Anti_Lock.isSelected()) antilock = true;
            if(jCheckBox_Roof.isSelected()) roof = true;
            if(jCheckBox_Camera.isSelected()) camera = true;
            if(jCheckBox_VoiceControl.isSelected()) voice = true;
            if(jCheckBox_Anti_Theft.isSelected()) antitheft = true;
            if(jCheckBox_Fingerprint.isSelected()) fingerprint = true;
            if(jCheckBox_Maps.isSelected()) maps = true;
            if(jCheckBox_Speed_Sensor.isSelected()) speedsensors = true;
            if(jCheckBox_Crash_Sensor.isSelected()) crashsensor = true;

            C_CARS cars = new C_CARS(0,car_model, carmake, ownerId, price, address, seats, airbags, engine, doors, fuel_capa, fueltype, parking, antilock, roof, age, camera, voice, antitheft, fingerprint, maps, speedsensors, crashsensor);
            if(new C_CARS().addNewCars(cars))
            {
                    JOptionPane.showMessageDialog(null,"New Cars Added To The System","Add Cars", 1);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Cars NOT Added To The System","Add Cars", 2);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage()+"Enter a Valid Owner Id", "Invalid Data",0);
        }

    }//GEN-LAST:event_jButton_Add_CarsActionPerformed

    private void jButton_Remove_CarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove_CarsActionPerformed

       try
        {
            //deleting the selected cars from the system
            int id = Integer.valueOf(jTextField_Ids.getText());

            C_CARS car = new C_CARS();

            if(jTextField_Ids.getText().trim().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Eneter the Cars ID", "Empty ID", 2);
            }
            else
            {
                //show a confirmation message before deleting the type
                int yes_or_no =JOptionPane.showConfirmDialog(null,"Do you want to Delete this Cars","Delete Cars",JOptionPane.YES_NO_OPTION);

                if(yes_or_no == JOptionPane.YES_OPTION )
                {
                    if(car.removeCars(id))
                    {
                        JOptionPane.showMessageDialog(null,"Cars Data Deleted", "Delete Cars",1);
                        
                        //clear all field values after deleting
                        jTextField_Ids.setText("");
                        jComboBox_Carmake.setSelectedItem(0);
                        jTextField_Car_Model.setText("");
                        jTextField_OwnerId.setText("");
                        jTextField_Price.setText("");
                        jTextArea_Address.setText("");
                        jSpinner_Seats.setValue(0);
                        jSpinner_AirBags.setValue(0);
                        jSpinner_Cylinders.setValue(0);
                        jSpinner_Doors.setValue(0);
                        jTextField_FuelCapa.setText("");
                        jComboBox_Fueltype.setSelectedItem(0);
                        jCheckBox_Parking_Sensor.setSelected(false);
                        jCheckBox_Anti_Lock.setSelected(false);
                        jCheckBox_Roof.setSelected(false);
                        jSpinner_Age.setValue(0);
                        jCheckBox_Camera.setSelected(false);
                        jCheckBox_VoiceControl.setSelected(false);
                        jCheckBox_Anti_Theft.setSelected(false);
                        jCheckBox_Fingerprint.setSelected(false);
                        jCheckBox_Maps.setSelected(false);
                        jCheckBox_Speed_Sensor.setSelected(false);
                        jCheckBox_Crash_Sensor.setSelected(false);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Operation Failed", "Delete Cars",2);
                    }
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage()+"Enter a Valid Cars ID", "Invalid ID",0);
        }
    }//GEN-LAST:event_jButton_Remove_CarsActionPerformed

    private void jButton_Search_CarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Search_CarActionPerformed
        // search the cars by id and dispay the car data
        try
        {
          int carId = Integer.valueOf(jTextField_Ids.getText());
          
          C_CARS  cars= new C_CARS().searchCars(carId);
          
          if(cars != null)
          {
              
              for(Object carmake : map.keySet())
              {
                  if(map.get(carmake).equals(cars.getCar_Make()))
                          jComboBox_Carmake.setSelectedItem(carmake);
              }  
              jTextField_Car_Model.setText(cars.getCar_Model());
              jTextField_OwnerId.setText(String.valueOf(cars.getOwnerId()));
              jTextField_Price.setText(String.valueOf(cars.getPrice()));
              jTextArea_Address.setText(cars.getAddress());
              jSpinner_Seats.setValue(cars.getSeats());
              jSpinner_AirBags.setValue(cars.getAir_bags());
              jSpinner_Cylinders.setValue(cars.getEngine());
              jSpinner_Doors.setValue(cars.getDoors());
              jTextField_FuelCapa.setText(String.valueOf(cars.getFuel_capa()));
              jComboBox_Fueltype.setSelectedItem(cars.getFuel_type());
              if(cars.isParking_sensors()) jCheckBox_Parking_Sensor.setSelected(true);
              if(cars.isAntilock()) jCheckBox_Anti_Lock.setSelected(true);
              if(cars.isRoof()) jCheckBox_Roof.setSelected(true);
              jSpinner_Age.setValue(cars.getAge());
              if(cars.isCamera()) jCheckBox_Camera.setSelected(true);
              if(cars.isVoice()) jCheckBox_VoiceControl.setSelected(true);
              if(cars.isAntitheft()) jCheckBox_Anti_Theft.setSelected(true);
              if(cars.isFingerprint()) jCheckBox_Fingerprint.setSelected(true);
              if(cars.isMaps()) jCheckBox_Maps.setSelected(true);
              if(cars.isSpeed_sensors()) jCheckBox_Speed_Sensor.setSelected(true);
              if(cars.isCrash_sensors()) jCheckBox_Crash_Sensor.setSelected(true);
          }
          else
          {
             JOptionPane.showMessageDialog(null,"Cars Not Found", "Error",0);  
          }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage()+"Enter a Valid Cars Id", "Invalid Id",0);
        }
        
    }//GEN-LAST:event_jButton_Search_CarActionPerformed

    private void jCheckBox_RoofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_RoofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_RoofActionPerformed

    private void jCheckBox_Parking_SensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_Parking_SensorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_Parking_SensorActionPerformed

    private void jCheckBox_CameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_CameraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_CameraActionPerformed

    private void jButton_Show_CarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Show_CarsActionPerformed
        //show all cars in a new form
         
        SHOW_CARS_WINDOW showcarsform = new SHOW_CARS_WINDOW();
        showcarsform.setVisible(true);
        this.setVisible(false);                                    
    }//GEN-LAST:event_jButton_Show_CarsActionPerformed

    private void jComboBox_FueltypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_FueltypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_FueltypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CARS_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CARS_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CARS_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CARS_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CARS_WINDOW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_Cars;
    private javax.swing.JButton jButton_Edit_Cars;
    private javax.swing.JButton jButton_Remove_Cars;
    private javax.swing.JButton jButton_Search_Car;
    private javax.swing.JButton jButton_Show_Cars;
    private javax.swing.JCheckBox jCheckBox_Anti_Lock;
    private javax.swing.JCheckBox jCheckBox_Anti_Theft;
    private javax.swing.JCheckBox jCheckBox_Camera;
    private javax.swing.JCheckBox jCheckBox_Crash_Sensor;
    private javax.swing.JCheckBox jCheckBox_Fingerprint;
    private javax.swing.JCheckBox jCheckBox_Maps;
    private javax.swing.JCheckBox jCheckBox_Parking_Sensor;
    private javax.swing.JCheckBox jCheckBox_Roof;
    private javax.swing.JCheckBox jCheckBox_Speed_Sensor;
    private javax.swing.JCheckBox jCheckBox_VoiceControl;
    private javax.swing.JComboBox<String> jComboBox_Carmake;
    private javax.swing.JComboBox<String> jComboBox_Fueltype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Title;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_Age;
    private javax.swing.JSpinner jSpinner_AirBags;
    private javax.swing.JSpinner jSpinner_Cylinders;
    private javax.swing.JSpinner jSpinner_Doors;
    private javax.swing.JSpinner jSpinner_Seats;
    private javax.swing.JTextArea jTextArea_Address;
    private javax.swing.JTextField jTextField_Car_Model;
    private javax.swing.JTextField jTextField_FuelCapa;
    private javax.swing.JTextField jTextField_Ids;
    private javax.swing.JTextField jTextField_OwnerId;
    private javax.swing.JTextField jTextField_Price;
    // End of variables declaration//GEN-END:variables
}
